POST http://localhost:3003/api/blogs
Content-Type: application/json
//Authorization: Bearer ...

{
    "title": "blogi ilman lisääjää 4",
    "author": "Joku uusi author",
    "url": "http://url.com"
}